{
 "title": "Inference Classifier App Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "timeframe", "query": "1m, 5m, 15m, 1h, 6h, 12h, 1d" }
  ]
 },
 "panels": [
  {
   "title": "Application start time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "application_started_time_seconds",
     "legendFormat": "App {{label_name}}{{version}}"
    }
   ]
  },
  {
   "title": "Stored Responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(sentiment) (app_stored_responses_by_sentiment_current)"
    }
   ]
  },
  {
   "title": "Inference Latency Histogram By Sentiment",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(le) (rate(app_inference_latency_seconds_bucket{le=\"+Inf\", outcome=\"pos\"}[$__rate_interval]))",
     "legendFormat": "Pos"
    },
    {
     "expr": "sum by(le) (rate(app_inference_latency_seconds_bucket{le=\"+Inf\", outcome=\"neg\"}[$__rate_interval]))",
     "legendFormat": "Neg"
    }
   ]
  },
  {
   "title": "Inference Requests Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(sentiment) (rate(app_inference_success_total[$timeframe]))"
    }
   ]
  },
  {
   "title": "Average text input length",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "app_average_text_length", "legendFormat": "App {{label_name}}{{version}}" }
   ]
  }
 ]
}