{
 "title": "Experiment dashboard Copy",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Cache Hit Rate (image=v2)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(app_cache_hits_total{application=\"app\", version=\"v2\"}[$__rate_interval]) / on (application) rate(app_inference_requests_total{application=\"app\", version=\"v2\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "95th % avg Inference Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(app_inference_latency_seconds_bucket[$__rate_interval])) by (le, version))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inference Throughput Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "rate(app_inference_requests_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}