model:
  image: ghcr.io/remla25-team6/model-service:latest
  host: model-service:8080

app:
  image: ghcr.io/remla25-team6/app:latest

metrics:
  enabled: true
  port: 8080
  path: /actuator/prometheus
  serviceMonitor:
    enabled: true
    interval: 15s
    scrapeTimeout: 15s

secret:
  foo: PGV4YW1wbGVfc2VjcmV0Pg==

sharedVolume:
  path: /mnt/shared


grafana:
  dashboard:
    enabled: true
    # namespace: monitoring
    jsonFileName: app-custom-dashboard.json