model:
  image: ghcr.io/remla25-team6/model-service:latest
  image2: ghcr.io/remla25-team6/model-service:latest
  host: model-service:8080
  mlModelVersion: "v0.1.0"
  mlModelVersion2: "v0.1.0"

app:
  image: ghcr.io/remla25-team6/app:latest
  image2: ghcr.io/remla25-team6/app:latest

metrics:
  enabled: true
  port: 8080
  path: /actuator/prometheus
  serviceMonitor:
    enabled: true
    interval: 15s
    scrapeTimeout: 15s

secret:
  foo: PGV4YW1wbGVfc2VjcmV0Pg==

modelCacheVolume:
  path: /mnt/shared


grafana:
  dashboard:
    enabled: true
    # namespace: monitoring
    jsonFileName: app-custom-dashboard.json

# Rate limiter (see ratelimit-configmap and envoyfilter)
rateLimit:
  enabled: true
  userLimit: 20  # requests per minute per user