model:
  image: ghcr.io/remla25-team6/model-service:0.0.3-pre.20250506.194625
  url: http://model-service:8080

app:
  image: ghcr.io/remla25-team6/app:0.0.4-pre.20250506.183739

secret:
  foo: PGV4YW1wbGVfc2VjcmV0Pg==

sharedVolume:
  path: /mnt/shared