model:
  image: ghcr.io/remla25-team6/model-service:0.2.2-pre.20250609.165306
  image2: ghcr.io/remla25-team6/model-service:0.2.2-pre.20250609.165306
  host: model-service:8080
  mlModelVersion: "v0.1.0"
  mlModelVersion2: "v0.1.0"

app:
  image: ghcr.io/remla25-team6/app:0.1.1
  image2: ghcr.io/remla25-team6/app:0.1.0-experimental #experimental version

metrics:
  enabled: true
  port: 8080
  path: /actuator/prometheus
  serviceMonitor:
    enabled: true
    interval: 15s
    scrapeTimeout: 15s

secret:
  foo: PGV4YW1wbGVfc2VjcmV0Pg==

modelCacheVolume:
  path: /mnt/shared


grafana:
  dashboard:
    enabled: true
    # namespace: monitoring
    jsonFileName: app-custom-dashboard.json
    experimentJSON: experiment-dashboard.json