  services:
    model_service:
      image: ${MODEL_IMAGE}
      environment:
        - ML_MODEL_VERSION=${ML_MODEL_VERSION}
      container_name: model-service
      restart: unless-stopped
      volumes:
        - model_cache:/app/model_cache
      secrets:
        - example_secret

    app:
      image: ${APP_IMAGE}
      ports:
        - "8080:8080"
      environment:
        - MODEL_URL=http://model-service:8080
      depends_on:
        - model_service
      container_name: app
      restart: unless-stopped
      secrets:
        - example_secret

  secrets:
    example_secret:
      file: ./secrets/example_secret.txt

  volumes:
    model_cache: