# finalization.yml
---
# Ansible playbook for finalizing steps
- name: Finalize Kubernetes cluster setup from finalization workbook
  hosts: 192.168.56.100
  become: true

  vars:
    metallb_url: "https://raw.githubusercontent.com/metallb/metallb/v0.14.9/config/manifests/metallb-native.yaml"  # according to assignment
    metallb_crd: "/tmp/metallb-native.yaml"
    ip_pool_range: "192.168.56.90-192.168.56.99"  # According to assignment
    kubeconfig_src: "/etc/kubernetes/admin.conf"

  tasks:
    # A2: Step 20
    - name: Download MetalLB CRDs
      get_url:
        url: "{{ metallb_url }}"
        dest: "{{ metallb_crd }}"
        mode: '0644'

    - name: Apply MetalLB CRDs
      shell: kubectl apply -f "{{ metallb_crd }}" --kubeconfig="{{ kubeconfig_src }}" 
      register: crd_apply
      changed_when: "'created' in crd_apply.stdout or 'configured' in crd_apply.stdout"

    - name: Wait for MetalLB controller ready
      shell: |
        kubectl wait -n metallb-system \
          -l app=metallb,component=controller \
          --for=condition=ready pod --timeout=60s --kubeconfig="{{ kubeconfig_src }}"
      args:
        executable: /bin/bash
      register: wait_metallb
      until: wait_metallb.rc == 0

    - name: Create MetalLB IPAddressPool
      shell: |
        cat <<EOF | kubectl apply -f - --kubeconfig="{{ kubeconfig_src }}"
        apiVersion: metallb.io/v1beta1
        kind: IPAddressPool
        metadata:
          namespace: metallb-system
          name: default
        spec:
          addresses:
            - "{{ ip_pool_range }}"
        EOF
      args:
        executable: /bin/bash
      register: ippool_apply
      changed_when: "'created' in ippool_apply.stdout or 'configured' in ippool_apply.stdout"

    - name: Create MetalLB L2Advertisement
      shell: |
        cat <<EOF | kubectl apply -f - --kubeconfig="{{ kubeconfig_src }}"
        apiVersion: metallb.io/v1beta1
        kind: L2Advertisement
        metadata:
          namespace: metallb-system
          name: l2-adv
        spec:
          ipAddressPools:
            - default
        EOF
      args:
        executable: /bin/bash
      register: l2adv_apply
      changed_when: "'created' in l2adv_apply.stdout or 'configured' in l2adv_apply.stdout"

    # A2: Step 21
    - name: Add ingress-nginx Helm repository
      shell: KUBECONFIG="{{ kubeconfig_src }}" helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
      args:
        executable: /bin/bash
      register: helmrepo_ingress
      changed_when: "'already exists' not in helmrepo_ingress.stdout"

    - name: Update Helm repositories
      shell: KUBECONFIG="{{ kubeconfig_src }}" helm repo update
      args:
        executable: /bin/bash

    - name: Deploy Nginx Ingress Controller via Helm
      shell: |
        KUBECONFIG="{{ kubeconfig_src }}" helm install ingress-nginx ingress-nginx/ingress-nginx \
          --namespace ingress-nginx --create-namespace
      args:
        executable: /bin/bash
      register: helm_install_ingress
      changed_when: "'STATUS: deployed' in helm_install_ingress.stdout"

    # A2: Step 22
    - name: Add kubernetes-dashboard Helm repository
      shell: KUBECONFIG="{{ kubeconfig_src }}" helm repo add kubernetes-dashboard https://kubernetes.github.io/dashboard/
      args:
        executable: /bin/bash
      register: helmrepo_dash
      changed_when: "'already exists' not in helmrepo_ingress.stdout"

    - name: Update Helm repositories
      shell: KUBECONFIG="{{ kubeconfig_src }}" helm repo update
      args:
        executable: /bin/bash

    - name: Deploy Kubernetes Dashboard via Helm
      shell: |
        KUBECONFIG="{{ kubeconfig_src }}" helm install kubernetes-dashboard kubernetes-dashboard/kubernetes-dashboard \
          --namespace kubernetes-dashboard --create-namespace
      args:
        executable: /bin/bash
      register: helm_install_dash
      changed_when: "'STATUS: deployed' in helm_install_dash.stdout"

    - name: Create ServiceAccount for dashboard login
      shell: |
        cat <<EOF | kubectl apply -f - --kubeconfig="{{ kubeconfig_src }}"
        apiVersion: v1
        kind: ServiceAccount
        metadata:
          name: admin-user
          namespace: kubernetes-dashboard
        EOF
      args:
        executable: /bin/bash

    - name: Create ClusterRoleBinding for admin-user
      shell: |
        cat <<EOF | kubectl apply -f - --kubeconfig="{{ kubeconfig_src }}"
        apiVersion: rbac.authorization.k8s.io/v1
        kind: ClusterRoleBinding
        metadata:
          name: admin-user-binding
        roleRef:
          apiGroup: rbac.authorization.k8s.io
          kind: ClusterRole
          name: cluster-admin
        subjects:
        - kind: ServiceAccount
          name: admin-user
          namespace: kubernetes-dashboard
        EOF
      args:
        executable: /bin/bash

    - name: Create Ingress for Kubernetes Dashboard
      shell: |
        cat <<EOF | kubectl apply -f - --kubeconfig="{{ kubeconfig_src }}"
        apiVersion: networking.k8s.io/v1
        kind: Ingress
        metadata:
          name: kubernetes-dashboard-ingress
          namespace: kubernetes-dashboard
          annotations:
            nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        spec:
          rules:
          - host: dashboard.local
            http:
              paths:
              - path: /
                pathType: Prefix
                backend:
                  service:
                    name: kubernetes-dashboard
                    port:
                      number: 443
        EOF
      args:
        executable: /bin/bash

    # A2: Step 23: Install Istio via istioctl
    - name: Install Istio CLI binary
      unarchive:
        src: ./istio-1.25.2-linux-amd64.tar.gz
        dest: /home/vagrant
        remote_src: false
      register: istio_unpacked

    - name: Add istioctl to PATH for vagrant
      lineinfile:
        dest: /home/vagrant/.bashrc
        line: 'export PATH=$PATH:/home/vagrant/istio-1.25.2/bin'
      when: istio_unpacked.changed

    - name: Run istioctl install
      command: istioctl install --set profile=demo -y
      args:
        chdir: /home/vagrant/istio-1.25.2
      when: install_istio | default(false)