# general.yml
---
# General Ansible playbook for both ctrl and worker nodes
- name: 
  become: true
  hosts: all

  tasks:
    - name: Disable Swap
      shell:
        cmd: swapoff -a
        register: swapoff
        changed_when: swapoff.rc == 0
    
    - name: Disable Swap in fstab
      lineinfile:
        path: /etc/fstab
        regexp: '^([^#].*\sswap\s+sw\s+.*)$'
        state: absent
        backup: yes

    # TODO: Take SSH key from a .pub file from directory in the repository
    - name: Set authorized key for user ubuntu copying it from current user
      ansible.posix.authorized_key:
        user: ubuntu
        state: present
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

    # Step 6
    - name: Create k8s.conf file
      ansible.builtin.copy:
        dest: /etc/modules-load.d/k8s.conf
        content: |
          overlay
          br_netfilter
        owner: root
        group: root
        mode: '0644'
    
    - name: Load br_netfilter module
      community.general.modprobe:
        module: br_netfilter
        state: present
    
    # Step 7
    - name: Enable IPv4 forwarding
      ansible.builtin.sysctl:
        name: "{{ item }}"
        value: 1
        state: present
        reload: yes
      loop:
        - net.ipv4.ip_forward
        - net.bridge.bridge-nf-call-iptables
        - net.bridge.bridge-nf-call-ip6tables

    # Step 8
    - name: Manage /etc/hosts
      ansible.builtin.blockinfile:
        path: /etc/hosts
        block: "{{ lookup('template', 'templates/hosts.j2') }}"
        owner: root
        group: root
        mode: '0644'
    
    
