# node.yml
---
# Ansible playbook for worker nodes
- name: Setting up worker node from node workbook
  hosts: node-* 
  become: true
  tasks:
    - import_tasks: general.yml

    # A2: Step 18
    - name: Generate join command on controller
      shell: kubeadm token create --print-join-command
      register: join_command
      delegate_to: ctrl
      retries: 15
      delay: 15

    - name: Join the Kubernetes cluster
      shell: "{{ join_command.stdout }} --ignore-preflight-errors=all"
      args:
        creates: /etc/kubernetes/kubelet.conf
