apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app-v1
  labels:
    app: {{ .Release.Name }}-app
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-app
      version: v1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-app
        version: v1
    spec:
      containers:
        - name: app
          image: {{ .Values.app.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: MODEL_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-configmap
                  key: model.host
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app-v2
  labels:
    app: {{ .Release.Name }}-app
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-app
      version: v2
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-app
        version: v2
    spec:
      containers:
        - name: app
          image: {{ .Values.app.image2 }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: MODEL_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-configmap
                  key: model.host