apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ .Release.Name }}-app-dr
spec:
  host: {{ .Release.Name }}-app
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpHeaderName: x-version
  subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2