{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-app
  labels:
    release: prometheus-stack # DO NOT CHANGE THIS
    namespace: monitoring # This maybe breaks it idk at this point
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-app
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: metrics
      path: {{ .Values.metrics.path }}
      interval: {{ .Values.metrics.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout }}
      relabelings:
      - sourceLabels: [__meta_kubernetes_pod_label_version]
        targetLabel: version
        action: replace
{{- end }}