apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-entry-service
spec:
  gateways:
  - {{ .Release.Name }}-gateway
  hosts:
  - "*"
  http:
    - match:
        - headers:
            x-version:
              exact: v2
      route:
        - destination:
            host: {{ .Release.Name }}-app
            subset: v2
    - match:
        - headers:
            x-version:
              exact: v1
      route:
        - destination:
            host: {{ .Release.Name }}-app
            subset: v1
    - route:
      - destination:
          host: {{ .Release.Name }}-app
        weight: 90
      - destination:
          host: {{ .Release.Name }}-app
        weight: 10       