apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-entry-service
spec:
  gateways:
  - {{ .Release.Name }}-gateway
  hosts:
  - "*"
  http:
  - match:
      - uri:
          prefix: /
    route:
      - destination:
          host: {{ .Release.Name }}-app
          subset: v1
        weight: 90
      - destination:
          host: {{ .Release.Name }}-app
          subset: v2
        weight: 10