apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ .Release.Name }}-{{ .Values.model.serviceName }}-dr
spec:
  host: {{ .Release.Name }}-{{ .Values.model.serviceName }}
  subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2