apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-model-service-v1
  labels:
    app: {{ .Release.Name }}-model-service
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-model-service
      version: v1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-model-service
        version: v1
    spec:
      containers:
        - name: model-service
          image: {{ .Values.model.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /app/model_cache
              name: model-cache-volume
      volumes:
        - name: model-cache-volume
          hostPath:
            path: {{ .Values.modelCacheVolume.path }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-model-service-v2
  labels:
    app: {{ .Release.Name }}-model-service
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-model-service
      version: v2
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-model-service
        version: v2
    spec:
      containers:
        - name: model-service
          image: {{ .Values.model.image2 }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /app/model_cache
              name: model-cache-volume
      volumes:
        - name: model-cache-volume
          hostPath:
            path: {{ .Values.modelCacheVolume.path }}