apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.model.serviceName }}
spec:
  selector:
    app: {{ .Release.Name }}-{{ .Values.model.serviceName }}
  ports:
    - port: 8080
      targetPort: 8080