{{- if .Values.rateLimit.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: rate-limit-model-service
  namespace: {{ .Release.Namespace | default "default" }}
spec:
  workloadSelector:
    labels:
      app: {{ .Release.Name }}-model-service
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.filters.http.local_ratelimit
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
          stat_prefix: model_service_rate_limiter
          token_bucket:
            max_tokens: {{ .Values.rateLimit.userLimit }}
            tokens_per_fill: {{ .Values.rateLimit.userLimit }}
            fill_interval: 60s
          filter_enabled:
            default_value:
              numerator: 100
              denominator: HUNDRED
          filter_enforced:
            default_value:
              numerator: 100
              denominator: HUNDRED
          response_headers_to_add:
            - header:
                key: x-local-rate-limit
                value: 'true'
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: rate-limit-app-service
  namespace: {{ .Release.Namespace | default "default" }}
spec:
  workloadSelector:
    labels:
      app: {{ .Release.Name }}-app
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.filters.http.local_ratelimit
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
          stat_prefix: app_service_rate_limiter
          token_bucket:
            max_tokens: {{ .Values.rateLimit.userLimit }}
            tokens_per_fill: {{ .Values.rateLimit.userLimit }}
            fill_interval: 60s
          filter_enabled:
            default_value:
              numerator: 100
              denominator: HUNDRED
          filter_enforced:
            default_value:
              numerator: 100
              denominator: HUNDRED
          response_headers_to_add:
            - header:
                key: x-local-rate-limit
                value: 'true'
{{- end }}