apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-ratelimit-config
data:
  config.yaml: |
    # per-IP limit
    domain: ratelimit
    descriptors:
    - key: remote_address
      rate_limit:
        unit: minute
        requests_per_unit: {{ .Values.rateLimit.userLimit | default 10 }}

    # fallback per-path limit
    - key: PATH
      rate_limit:
        unit: minute
        requests_per_unit: {{ .Values.rateLimit.globalLimit | default 100 }}